### ISSUE TITLE
Frames missing in scipost's output

### ISSUE THREAD

**Issue by saimn** [olebole/python-cpl#15]
It looks like some frames (DATACUBE_FINAL, IMAGE_FOV) are missing in the scipost recipe output:
```
In [3]: cpl.Recipe('muse_scipost').output
Out[3]: 
{'PIXTABLE_OBJECT': ['AUTOCAL_MASK',
  'AUTOCAL_FACTORS',
  'RAMAN_IMAGES',
  'SKY_IMAGE',
  'SKY_MASK',
  'SKY_SPECTRUM',
  'SKY_LINES',
  'SKY_CONTINUUM']}
```
I'm now using this attribute to know which frames can be produced by a recipe, so I can make a special case for scipost but I'm reporting this here in case there is an easy solution (which is not obvious to me as these frames seems to be parsed with cpl functions ?).

**Comment by olebole** [comment]
That is a bug in `muse_scipost`: `DATACUBE_FINAL` and others are [not registered as output](https://salsa.debian.org/debian-astro-team/cpl-plugin-muse/blob/a93c2d45bfa0a8eb55ce7fc94622c687e868617e/recipes/muse_scipost_z.c#L157-164). I'll check that when I am back in the institute.

**Comment by saimn** [comment]
Ok, thanks.

**Comment by olebole** [comment]
FYI, I fixed this in the recipe's source; it should therefore appear in the next release.

**Comment by saimn** [comment]
Thanks, it works :)
```
In [3]: cpl.Recipe('muse_scipost').output
Out[3]: 
{'PIXTABLE_OBJECT': ['DATACUBE_FINAL',
  'IMAGE_FOV',
  'OBJECT_RESAMPLED',
  'PIXTABLE_REDUCED',
  'PIXTABLE_POSITIONED',
  'PIXTABLE_COMBINED',
  'AUTOCAL_MASK',
  'AUTOCAL_FACTORS',
  'RAMAN_IMAGES',
  'SKY_IMAGE',
  'SKY_MASK',
  'SKY_SPECTRUM',
  'SKY_LINES',
  'SKY_CONTINUUM']}
```
