### ISSUE TITLE
Can't find [Flat] files?

### ISSUE THREAD

**Issue by sirpercival** [olebole/python-cpl#4]
I'm not sure I understand how the tag system works. I'm trying to use the isaac_spc_flats recipe to create a master flat file. I've tested that my ElementTree + XPath parsing works as it's supposed to; when I then call the recipe with `master_sp_flat = isaac_spc_flat({'raw':flats})`, I get `[  ERROR] Cannot find flat frames in the input list`.

Is there some other way that the recipe is supposed to know what the flats are? Or am I missing something? Thanks!

**Comment by olebole** [comment]
I am not sure about isaac: what is the input tag needed here? I would guess that the input tag is "flat", and not "raw", so you could try
```
master_sp_flat = isaac_spc_flat({'flat':flats})
```

**Comment by sirpercival** [comment]
> I am not sure about isaac: what is the input tag needed here?

I really don't know... this is the problem I'm running into. Changing `raw` to `flat` (and `sp_flat`, I tried that too) led to the same error. The particular recipe is in [this pdf](ftp://ftp.eso.org/pub/dfs/pipelines/isaac/isaac-pipeline-manual-1.4.pdf) on page 48.

**Comment by olebole** [comment]
Try 'SP_FLAT' (capital letters), as stated in the manual.

**Comment by sirpercival** [comment]
Aha! That's it, and I now understand :) Thank you!
