### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by sirpercival** [olebole/python-cpl#5]
Hi again,

This one is something about an incorrect input or something? I really don't know. I've made a gist of the traceback, my code, and the recipe that's throwing the error. https://gist.github.com/sirpercival/7c961e8c53cb112eb35e

I really appreciate your help with this stuff.

**Comment by olebole** [comment]
The recipe threw an error:
```
Illegal input: "empty (sub)expression" from regcomp()=14. regexp='', invert=0 (14) in cpl_propertylist_copy_property_regexp() (cpl_propertylist.c:6461)
Illegal input (14) in isaac_spc_flat() (isaac_spc_flat.c:349) 
```
The cause of the error is within the recipe; so you should debug the isaac recipe, or ask the ESO about this. It is not caused by python-cpl.

**Comment by sirpercival** [comment]
Oh, thanks!
