### ISSUE TITLE
Example of using CPL routines directly

### ISSUE THREAD

**Issue by ivh** [olebole/python-cpl#6]
I suspect this is beyond the scope and purpose of python-cpl, but I hope you forgive my asking anyway: Is there a way to use CPL-internal functions directly from Python scripts, i.e. without a recipe? If this is possible, could you include an example in the documentation?

I want to test certain CPL-routines with fake data and doing this from Python scripts directly would save me some effort.

**Comment by olebole** [comment]
Python-cpl is designed to run recipes only; so you would need to wrap the routine into a recipe. Depending on your needs, this may be however simple -- you could take the test recipe as an example.

**Comment by ivh** [comment]
Ok, thanks!
